# Generated by Django 4.0.3 on 2022-03-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='course',
        ),
    ]
